utilitywarehouse/wiresteward

- wireguard.go
Using `ReplacePeers` causes a small hiccup while wireguard re-configures. Instead, we could just patch the config by identifying peers to be removed and upserting the rest.
Additionally, we use `ReplaceAllowedIPs` for peers, which doesn't seem to affect connectivity.
> Optimise replacing peer config

- README.md
- agent.json.example
- config.go
- config_test.go
- main.go
Left whatever is tied to netlink as device, since that is closer to the names
used in the package.
> Rename devices to interfaces

- main.go
```
^CINFO: (wg-uw-dev-aws) 2020/07/30 08:15:26 Device closing
-agent
Run application in "agent" mode
-config string
Config file (only used in agent mode)
-server
Run application in "server" mode
-version
Prints out application version
```
> Avoid printing flag defaults when closing agent

- agent_http.go
By default ServeMux will match everything:
https://golang.org/pkg/net/http/#ServeMux
> Handle renew tokens only on URI "/"

- README.md
- agent.go
- agent.json.example
- config.go
- config_test.go
- devicemanager_darwin.go
This is to stay consistent with upstream naming (such as in the wireguard
packages).
> Rename interface to device

- device.go
`wg0` created by wiresteward
`wg1` created by wg-quick
```
2020/08/20 13:54:38 diff:   &netlink.GenericLink{
LinkAttrs: netlink.LinkAttrs{
- 		Index:        30,
+ 		Index:        29,
MTU:          8921,
- 		TxQLen:       0,
+ 		TxQLen:       1000,
- 		Name:         "wg0",
+ 		Name:         "wg1",
HardwareAddr: s"",
Flags:        s"up|pointtopoint",
... // 19 identical fields
},
LinkType: "wireguard",
}
```
> Set default tx qlen for server device

- config.go
- config_test.go
- lease.go
- lease_test.go
- main.go
- oauth2.go
- serve.go
- server.json.example
- terraform/ignition/ignition.tf
- terraform/ignition/io.tf
- terraform/ignition/resources/wiresteward-config.json.tmpl
Remove the leaseTime configuration option for server. The expiry time
of a lease is now the same as the expiry time of the provided access
token.
> Use access token expiry time for leases

- agent.go
- config.go
- config_test.go
- device.go
- devicemanager.go
- devicemanager_darwin.go
- devicemanager_linux.go
- lease.go
- logger.go
- main.go
- oauth2.go
- serve.go
- wireguard.go
Borrow the logger from wireguard device package to bring consistency across
application and tun devices logs
> Use global logger for all application logs

- README.md
- agent.go
- agent.json.example
- config.go
- config_test.go
Wiresteward is now designed to work with oauth2 access tokens, so we
should rename occurences of 'oidc' to reflect design.
> Use oauth instead of oidc

- main.go
I noticed that the v0.1.0-rc2 release was reporting a different version that is staticly set as a const in main.go. As we're generating binaries with goreleaser, we can take advantage of the ldflags that it sets when it builds:
- https://goreleaser.com/environment/#using-the-mainversion
```
$ ./dist/main_darwin_amd64/wiresteward -version
INFO: wiresteward: 2020/09/02 10:27:45 version=0.1.0-rc300 commit=d21c79225e8e172c321e801646817c507926be4f date=2020-09-02T09:27:21Z builtBy=goreleaser
```
> Use goreleaser ldflags for version

- terraform/aws/io.tf
When the instance is re-created the eip resource does not change but its
allocation does. The output are stale until the next time terraform
plans.
> terraform/aws: get private addresses from instances

- devicemanager_linux.go
That way we can have many peers per device.
> Add GW in linux routes.

- terraform/aws/main.tf
- terraform/gcp/main.tf
Flatcar Linux stable releases now come with kernel 5.x and wireguard.
> terraform: switch to flatcar stable

- device.go
- devicemanager.go
- main.go
Set `WIRESTEWARD_USE_KERNEL_WIREGUARD` to a non-empty value to enable this experimental behaviour.
> Add kernel-based implementation for agent

- agent.go
- main.go
When using wireguard devices, these will not get cleaned up when the
agent dies.
> Fix cleanup of devices on error

- go.mod
- go.sum
- oauth2.go
https://github.com/nirasan/go-oauth-pkce-code-verifier is:
1. Not using secure random ("math/rand")
2. Uses the wrong length for code verifier
3. Is not using the full allowed charset the the code verifier
Fix the above, and remove the dependency on the untrusted libarary.
> Use better crypto for PKCE

- main.go
The default value will always be set and wiresteward -server will error and not
start.
> Remove flag check to allow starting -server

- examples/wiresteward.service
https://www.linuxtopia.org/Linux_Firewall_iptables/x4700.html#:~:text=The%20%2D%2Dclamp%2Dmss%2Dto,reasonable%20value%20for%20most%20applications.
Applications that are running on the host already do this via default
`advmss`:
> If it is not given, Linux uses a default value calculated from the
> first hop device MTU.
From: https://www.systutorials.com/docs/linux/man/8-ip-route/
OpenWRT thread on why set this in POSTROUTING:
https://openwrt-devel.openwrt.narkive.com/1ikg7NtX/mss-clamping-in-postrouting-instead-of-forward
`--clamp-mss-to-pmtu` as a "fix" for routing problems:
https://tldp.org/HOWTO/Adv-Routing-HOWTO/lartc.cookbook.mtu-mss.html
> Clamp mss to pmtu for agent running on Linux

- terraform/aws/main.tf
Instance auto-updates, we do not to redeploy it as a new AMI becomes
available
> Ignore AMI changes

- terraform/aws/main.tf
- terraform/gcp/main.tf
- terraform/ignition/io.tf
- terraform/ignition/resources/wiresteward-config.json.tmpl
- Change firewall to allow public traffic on http ports to reach traefik
- Remove the local server listen address from the config to allow both the old
and new setups to work. This should be re-added when we delete the load
balancers in front of the instances.
> Prepare terraform form aws/gcp v0.2.0

- agent.go
- devicemanager.go
Update the device manager token and trigger a lease renew via the related
channel/loop mechanism, so in case of failure the lease is retried. This could
mitigate the scenario where an initial connect attempt fails because we try to
connect to an unhealthy server peer and as a result, a connection is never
established unless we go via the manual trigger again (and again).
> Retry when agent triggered lease renewal fails

- agent.go
In case the callback url contains stale data and someone uses browser's
refresh button.
> Redirect to root page to avoid refresh confusion

- terraform/matchbox/dns.tf
- terraform/matchbox/main.tf
- terraform/matchbox/net.tf
- terraform/matchbox/variables.tf
The latest releases of Flatcar stable enable the systemd-resolved stub resolver. Although I'm not sure why, this seems to ignore the DNS server set on the link (even though systemd-resolved does properly populate resolv.conf with it).
This commit sets the DNS server globally in /etc/systemd/resolved.conf. It also adds the other Cloudflare DNS address 1.0.0.1 which we're providing via DHCP on other instances.
I've made the nameservers configurable too, to avoid having to edit the module if we want to change this in future.
> tf/matchbox: move DNS configuration to resolved.conf

- agent.go
- config.go
- config_test.go
- devicemanager.go
Observed that when rolling wiresteward servers, the agent can stuck while trying
to hit a server that is unavailable. This introduces a timeout on the agent's
http client, so requests can terminate faster, giving better failover times
> Add a default configurable timeout on agent http client

- config.go
- config_test.go
- device.go
- go.mod
- go.sum
- lease.go
- lease_test.go
- metrics.go
- metrics_test.go
- ping.go
- serve.go
Long form "why": https://tailscale.com/blog/netaddr-new-ip-type-for-go/
- much simpler logic for finding available address
- remove reliance on ipv4
- smaller IP object
- more performant IP calculations
> Switch to using inet.af/netaddr over std lib net

- agent_http.go
- config.go
- devicemanager.go
- healthcheck.go
- healthcheck_test.go
A larger one for "healthy" checking. After the first failure - go down
to 1s.
That means by default we check every 10s. If a healthcheck fails, we
reset the ticker to 1s, and continue checking.
After 3 failures we failover (13s max, 8s average).
If instead we get a healthy check - reset the "unhealthyCount" and reset
the ticker, back to 10s interval.
Compared to previous implementation - our average failover time goes up
from 3.5s to 8s, ~2.3x increase. But our healthcheck load decreases 10x,
from 1s to 10s.
> Use two intervals for healthchecking

- devicemanager.go
- oauth2.go
- Agent avoids requesting a new lease with an expired token
- server avoids requests to the introspection endpoint for expired tokens.
> Check if tokens are expired before further actions.

- terraform/aws/io.tf
- terraform/aws/main.tf
- terraform/aws/s3-userdata.tf
Userdata from an aws instance can be retrieved with "DescribeInstance",
which is a fairly common "read only" permission. By storing the userdata
in s3 we are not exposing the sensitive values
> aws: retrieve userdata from s3

- terraform/matchbox/main.tf
- terraform/matchbox/net.tf
- terraform/matchbox/variables.tf
- Allow wiresteward instances to specify disk types
- Opinionated change for network setup. Specify only public vlan interface and
assume that by default instance native vlan will be the private one. Works
better with moonshot 45XGc switches.
> Change on-prem matchbox module net setup and allow disks

- Makefile
- devicemanager.go
- oauth2.go
- oauth2_test.go
Currently when token expires, wiresteward goes into generic backoff
retry loop, and keeps printing error logs for every device, saying that
the token is expired.
Wiresteward will never exit this condition on its own, and user needs to
renew the token.
If we get an error about expired token on renew, exit the loop and don't
retry.
> Exit retry loop if the token is expired

- terraform/ignition/ignition.tf
- terraform/ignition/io.tf
Add ability to omit locksmithd service in case this is passed as an additional
ignition service. Ignition > 2.0.0 will mark the config as invalid if a service
is defined twice. Useful for our pxe setups.
> Make setting locksmithd systemd service optional

- .goreleaser.yml
Manage via `brew services`...
```
brew sevices start wiresteward-agent
brew sevices stop wiresteward-agent
brew sevices restart wiresteward-agent
```
This will look for the config file in the default location `/etc/wiresteward/config.json`
> Manage agent service

- .github/workflows/build.yaml
- .goreleaser.yml
Enable `brew install utilitywarehouse/tap/wiresteward`
I'd like to validate the release by merging & tagging `v0.2.6` before raising a PR to update the docs.
OSX/Linux users using Homebrew can then just `brew update && brew upgrade` to get a new version of Wiresteward.
Manage via `brew services` which will start up in agent mode as this is most common.
```
brew sevices start utilitywarehouse/tap/wiresteward
brew sevices stop utilitywarehouse/tap/wiresteward
brew sevices restart utilitywarehouse/tap/wiresteward
```
This will look for the config file in the default location `/etc/wiresteward/config.json`
> homebrew release

- .goreleaser.yml
Fix
```
==> Fetching utilitywarehouse/tap/wiresteward
==> Downloading https://github.com/utilitywarehouse/wiresteward/releases/download/v0.2.6-RC2/wiresteward_0.2.6-RC2_darwin_arm64
Already downloaded: /Users/rcrowe/Library/Caches/Homebrew/downloads/f44b81d6aeea39c102cc4c78277dbc234b3262e7d172d313310c91c04f03335c--wiresteward_0.2.6-RC2_darwin_arm64
==> Reinstalling utilitywarehouse/tap/wiresteward
Error: Formula specified both service and plist
Error: Cannot link wiresteward
```
> Fix homebrew error "Formula specified both service and plist"

- terraform/aws/main.tf
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#user_data_replace_on_change
Our update script currently relies on the instances being replaced on
userdata change
> Replace instance on userdata change - AWS

- terraform/aws/main.tf
Lower costs and better performance compared to t2
> Default aws deployment to t3a instance family

- terraform/aws/ignition_config.json
- terraform/aws/main.tf
- terraform/aws/s3-userdata.tf
`template_file` is deprecated in favour of `templatefile` function
https://registry.terraform.io/providers/hashicorp/template/latest/docs#deprecation
> Replace deprecated template_file
